## **Tag along code**


Convention for importing numpy

In [2]:
import numpy as np 

In [3]:
arr = [6, 7, 8, 9]

print(type(arr))

<class 'list'>


In [4]:
a = np.array(arr)

print (type (a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(4,)


In [6]:
print (a.ndim)

1


In [7]:
b = np.array ([[1, 2, 3], [4, 5, 6]])

print (b)

[[1 2 3]
 [4 5 6]]


In [8]:
print(b.ndim)

b. shape

2


(2, 3)

In [1]:
arr = [6, 7, 8, 9]

print(type(arr))

<class 'list'>


In [9]:
a = np.array (arr)

print (type(a))

print(a.shape)

<class 'numpy.ndarray'>
(4,)


In [10]:
print (a.dtype)

int64


In [11]:
print(a.ndim)

1


In [12]:
b = np.array ([[1, 2, 3], [4, 5, 6]])
print (b)

[[1 2 3]
 [4 5 6]]


In [13]:
print (b.ndim)

2


In [14]:
b. shape

(2, 3)

 Inbuilt functions that can be used to initialize numpy

In [15]:
np.zeros ( (2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones ( (2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.identity (3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Inter operability of arrays and scalar 

In [18]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])


In [19]:
d = np.array ([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])


In [25]:
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [26]:
c * d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [27]:
5 / d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [29]:
c**2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

Indexing with arrays & using arrays for data processing 

In [32]:
a

array([6, 7, 8, 9])

In [30]:
a[0]

6

In [31]:
a[3]

9

In [33]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
b[0, 0]

1

In [35]:
b[1, 2]

6

In [37]:
c

array([[9., 8., 7.],
       [1., 2., 3.]])

In [38]:
c[0,1]

8.0

In [39]:
e = np.array ([[10, 11, 12], [13, 14, 15],

[16, 17, 18], [19, 20, 21]])

In [40]:
e[:3,:2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [41]:
e[[2, 0, 3, 1], [2, 1, 0, 2]]

array([18, 11, 19, 15])

In [42]:
e[e>15]

array([16, 17, 18, 19, 20, 21])

## Convention for importing Pandas

In [43]:
import pandas as pd
import numpy as np

In [45]:
days = pd.Series(["Monday","Tuesday", "Wednesday"])
print(days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [46]:
days_list = np.array(['Monday', 'Tuesday', 'Wednesday'])

In [47]:
numpy_days = pd.Series(days_list)

In [48]:
print(numpy_days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [50]:
days = pd.Series(["Monday","Tuesday", "Wednesday"], index = ['a', 'b', 'c'])
print(days)

a       Monday
b      Tuesday
c    Wednesday
dtype: object


In [52]:
days[0]

'Monday'

In [53]:
days[1:]

b      Tuesday
c    Wednesday
dtype: object

In [54]:
days['c']

'Wednesday'

In [51]:
days1 = pd.Series({'a': 'Monday', 'b':'Tuesday','c':'Wednesday'})
print(days1)

a       Monday
b      Tuesday
c    Wednesday
dtype: object


In [55]:
print(pd.DataFrame())

Empty DataFrame
Columns: []
Index: []


In [57]:
df_dict = {'Country': ['Ghana', 'Kenya', 'Nigeria', 'Togo'],
           'Capital': ['Accra',  'Nairobi','Abuja','Lome'],
            'Population': [10000, 8500, 35000, 12000 ],
            'Age': [60, 70, 80, 75]}

In [59]:
df = pd. DataFrame (df_dict, index = [2, 4, 6, 8])

df_list = [
            ['Ghana','Accra', 10000, 60],

            ['Kenya','Nairobi', 8500, 70],

            ['Nigeria','Abuja', 35000, 80],

            ['Togo',3, 'Lome', 12000, 75]]




## Data Types and Data Wrangling

Working with different types of data: text files, CS, JSON objects, HTML and databases.



In [65]:
csv_df = pd.read_csv ('/content/sample_data/california_housing_test.csv')

csv_df.to_csv ('sample_file.csv', index=False)

FileNotFoundError: ignored

In [66]:
csv_df = pd.read_csv ('/content/sample_data/california_housing_test.csv')

csv_df.to_csv ('/content/sample_data/california_housing_test.csv', index=False)

In [ ]:
excel_df = pd.read_excel('/content/sample_data/california_housing_test.xIsx')

excel_df.to_excel('/content/sample_data/california_housing_test.xIsx')

In [ ]:
htm1_df. = pd. read_htm1('http://www.webpage.com/sampledata.html')

htmI_df.to_htmI('sample_file.html')

In [ ]:
url='https://github.com/WalePhenomenon/climate_change/blob/master/fuel_fercl.csv?raw=true'

fuel_data = pd.read_csv(url, error_bad_lines=False)

fuel_data.describe(include= 'all')